defmodule TrifleApp.ExploreCoreTest do
  use ExUnit.Case, async: true

  alias TrifleApp.ExploreCore

  describe "format_number/1" do
    test "preserves trailing zeros for whole-number suffixes" do
      assert ExploreCore.format_number(390_000_000) == "390m"
      assert ExploreCore.format_number(100_000_000) == "100m"
    end

    test "trims decimal zeros for suffixes" do
      assert ExploreCore.format_number(1_000_000) == "1m"
      assert ExploreCore.format_number(1_500_000) == "1.5m"
    end
  end

  describe "format_nested_path/4" do
    test "escapes path components in generated html" do
      raw_path = "<img src=x onerror=alert(1)>"

      html =
        raw_path
        |> ExploreCore.format_nested_path([raw_path], %{})
        |> Phoenix.HTML.safe_to_string()

      assert String.contains?(html, "&lt;img src=x onerror=alert(1)&gt;")
      refute String.contains?(html, "<img src=x onerror=alert(1)>")
    end

    test "escapes transponder names in tooltip content" do
      path = "safe.path"

      html =
        path
        |> ExploreCore.format_nested_path([path], %{path => "<script>alert(1)</script>"})
        |> Phoenix.HTML.safe_to_string()

      assert String.contains?(html, "Generated by transponder:")
      assert String.contains?(html, "&lt;script&gt;alert(1)&lt;/script&gt;")
      refute String.contains?(html, "<script>alert(1)</script>")
    end
  end
end
