import Config

# Configure your database
config :trifle, Trifle.Repo,
  username: "postgres",
  password: "password",
  hostname: "postgres",
  database: "trifle_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :trifle, TrifleWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "ppvB4Hbwizt8mlVK13MXLvXSCbJRMeV3iZ9MzYc/Uf8JQz37T+cELXyT7y7AZ9QT",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:default, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :trifle, TrifleWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/trifle_web/(controllers|live|components)/.*(ex|heex)$",
      ~r"lib/trifle_app/(controllers|live|components)/.*(ex|heex)$",
      ~r"lib/trifle_api/(controllers|live|components)/.*(ex|heex)$",
      ~r"lib/trifle_admin/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :trifle, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Encryption config for local dev/migrations.
default_db_encryption_key = String.duplicate("0", 32)

db_encryption_key =
  case System.get_env("TRIFLE_DB_ENCRYPTION_KEY") do
    nil ->
      default_db_encryption_key

    "" ->
      default_db_encryption_key

    value ->
      case Base.decode64(value) do
        {:ok, key} when byte_size(key) == 32 -> key
        _ -> default_db_encryption_key
      end
  end

config :trifle, Trifle.Vault,
  ciphers: [
    default: {Cloak.Ciphers.AES.GCM, tag: "AES.GCM.V1", key: db_encryption_key}
  ]

# OpenAI configuration is now in runtime.exs to support .env loading

# config :trifle_stats,
#   driver: Mongo.start_link(url: "mongodb://mongo:27017/trifle"),
#   track_ranges: [:minute, :hour, :day, :week, :month, :quarter, :year],
#   separator: "::",
#   time_zone: "Europe/Bratislava",
#   time_zone_database: Tzdata.TimeZoneDatabase,
#   beginning_of_week: :monday
